services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: payana
      POSTGRES_PASSWORD: payana-#12G#23
      POSTGRES_DB: invoice_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: payana
      DB_PASSWORD: payana-#12G#23
      DB_NAME: invoice_db
      DB_PORT: 5432
      PORT: 3000
      SYNC_DB: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
